### ISSUE TITLE
Can not open AD hyperlink in QT wallet or in browser

### ISSUE THREAD

**Issue by bitsha256** [bitsuperlab/qt_play#6]

**Comment by clar** [comment]
By default, external links are forbidden in QT wallet. But i've comment out this checking codes when adding url bar.

**Comment by clar** [comment]
And as the url bar task is completed now, after merging these codes into DAC play, this issue should be gone.

**Comment by hackfisher** [comment]
Do you mean after merging, the external links could be open in the url bar?

**Comment by clar** [comment]
yes, i'm testing on my machine. if it's ok, i will comment here.

**Comment by clar** [comment]
https://github.com/bitsuperlab/web_play/commit/d8e0911129c1a3e29717b5b2c16d0f2cc7345203

**Comment by clar** [comment]
It works now.  Not only the external url reason, but also a QT bug related to links with target="_blank".
https://bugreports.qt.io/browse/QTBUG-42282
